server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/hpeng56/config-repo.git
          clone-on-start: true

logging:
  level:
    org.springframework.cloud: 'DEBUG'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}